---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "es-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 3  # Elasticsearch 节点数
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/elasticsearch:8.13.4
          env:
            - name: discovery.type
              value: "zen-disco"
            - name: "ES_JAVA_OPTS"
              value: "-Xms2g -Xmx2g"
          ports:
            - containerPort: 9200  # HTTP 请求端口
            - containerPort: 9300  # 节点间通信端口
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data  # 数据目录
      volumes:
        - name: es-data
          emptyDir: {}  # 使用空目录作为临时存储（数据将不会持久化）

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  clusterIP: None  # 集群内部无负载均衡
  ports:
    - name: http  # 为 9200 端口指定名称
      port: 9200
      targetPort: 9200
    - name: transport  # 为 9300 端口指定名称
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch  # 确保 Selector 与 Deployment 中的标签一致
